"""Enforce the reconstructed package boundaries from the source import graph."""

from __future__ import annotations

import ast
from collections.abc import Iterable
from pathlib import Path

SOURCE_ROOT = Path(__file__).resolve().parents[3] / "src" / "chronikwerk"
LEGACY_PACKAGES = frozenset({"app", "adapters", "domain", "config", "observability"})
RUNTIME_FEATURE_PACKAGES = frozenset(
    {"archiving", "documents", "operations", "storage", "web", "zammad"}
)
ALLOWED_FEATURE_DEPENDENCIES = {
    "configuration": frozenset(),
    "operations": frozenset({"configuration"}),
    "zammad": frozenset({"configuration"}),
    "documents": frozenset({"configuration", "operations", "zammad"}),
    "storage": frozenset({"documents"}),
    "archiving": frozenset({"configuration", "documents", "operations", "storage", "zammad"}),
    "web": frozenset({"configuration", "operations"}),
}
SHARED_LEAF_MODULES = frozenset(
    {"chronikwerk.failures", "chronikwerk.outbound", "chronikwerk.timestamps"}
)
PURE_ARCHIVING_FORBIDDEN_PACKAGES = frozenset(
    {"configuration", "documents", "operations", "storage", "web", "zammad"}
)
PURE_ARCHIVING_MODULES = frozenset(
    {
        "path",
        "notes",
        "error_messages",
        "error_policy",
    }
)


def _module_name(path: Path) -> str:
    """Convert one source path into its importable module name."""
    relative = path.relative_to(SOURCE_ROOT).with_suffix("")
    parts = list(relative.parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(("chronikwerk", *parts))


def _resolve_import(node: ast.ImportFrom, current_module: str) -> str | None:
    """Resolve an absolute or relative from-import to an absolute module name."""
    if node.level == 0:
        return node.module
    current_package = current_module.rsplit(".", 1)[0]
    package_parts = current_package.split(".")
    base_parts = package_parts[: len(package_parts) - node.level + 1]
    if node.module:
        base_parts.extend(node.module.split("."))
    return ".".join(base_parts) or None


def _imports(path: Path) -> Iterable[str]:
    """Yield every imported module represented in one Python source file."""
    current_module = _module_name(path)
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            yield from (alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            resolved = _resolve_import(node, current_module)
            if resolved:
                yield resolved
                if resolved == "chronikwerk":
                    yield from (f"chronikwerk.{alias.name}" for alias in node.names)


def _source_files() -> Iterable[Path]:
    """Yield maintained package sources while excluding generated bytecode."""
    return sorted(path for path in SOURCE_ROOT.rglob("*.py") if "__pycache__" not in path.parts)


def _feature_package(module: str) -> str | None:
    """Return the first package below chronikwerk for an internal module."""
    parts = module.split(".")
    if len(parts) >= 2 and parts[0] == "chronikwerk":
        return parts[1]
    return None


def _cross_package_private_module(source_module: str, imported_module: str) -> bool:
    """Detect imports of underscore modules from outside their owning package."""
    parts = imported_module.split(".")
    if parts[:1] != ["chronikwerk"]:
        return False
    try:
        private_index = next(
            index for index, part in enumerate(parts[1:], start=1) if part.startswith("_")
        )
    except StopIteration:
        return False
    target_package = ".".join(parts[:private_index])
    source_package = source_module.rsplit(".", 1)[0]
    return source_package != target_package and not source_package.startswith(target_package + ".")


def _architecture_node(module: str) -> str | None:
    """Return the dependency-graph node represented by an internal module."""
    if module in SHARED_LEAF_MODULES:
        return module
    feature = _feature_package(module)
    return feature if feature in ALLOWED_FEATURE_DEPENDENCIES else None


def _cycle_nodes(edges: dict[str, set[str]]) -> set[str]:
    """Return nodes left after topologically removing every acyclic dependency."""
    remaining = {node: set(dependencies) for node, dependencies in edges.items()}
    while ready := {node for node, dependencies in remaining.items() if not dependencies}:
        for node in ready:
            remaining.pop(node)
        for dependencies in remaining.values():
            dependencies.difference_update(ready)
    return set(remaining)


def test_reconstructed_source_imports_obey_architecture_boundaries() -> None:
    violations: list[str] = []
    edges: dict[str, set[str]] = {
        node: set() for node in (*ALLOWED_FEATURE_DEPENDENCIES, *SHARED_LEAF_MODULES)
    }
    for path in _source_files():
        source_module = _module_name(path)
        source_feature = _feature_package(source_module)
        source_leaf = path.stem
        for imported_module in _imports(path):
            imported_feature = _feature_package(imported_module)
            source_node = _architecture_node(source_module)
            imported_node = _architecture_node(imported_module)
            if source_node and imported_node and source_node != imported_node:
                edges[source_node].add(imported_node)
            if imported_feature in LEGACY_PACKAGES:
                violations.append(f"{source_module} imports legacy {imported_module}")
            if source_module in SHARED_LEAF_MODULES and imported_module.startswith("chronikwerk."):
                violations.append(
                    f"shared leaf {source_module} imports internal module {imported_module}"
                )
            if source_feature == "configuration" and imported_feature in RUNTIME_FEATURE_PACKAGES:
                violations.append(f"{source_module} imports runtime feature {imported_module}")
            if (
                source_feature in ALLOWED_FEATURE_DEPENDENCIES
                and imported_feature in ALLOWED_FEATURE_DEPENDENCIES
                and imported_feature != source_feature
                and imported_feature not in ALLOWED_FEATURE_DEPENDENCIES[source_feature]
            ):
                violations.append(
                    f"{source_module} imports forbidden feature dependency {imported_module}"
                )
            if source_feature == "archiving" and imported_feature == "web":
                violations.append(f"{source_module} imports delivery layer {imported_module}")
            if (
                source_feature == "archiving"
                and source_leaf in PURE_ARCHIVING_MODULES
                and imported_feature in PURE_ARCHIVING_FORBIDDEN_PACKAGES
            ):
                violations.append(f"{source_module} is pure but imports {imported_module}")
            if _cross_package_private_module(source_module, imported_module):
                violations.append(f"{source_module} imports private module {imported_module}")

    if cycles := _cycle_nodes(edges):
        violations.append(f"dependency cycle includes: {', '.join(sorted(cycles))}")

    assert not violations, "\n".join(sorted(violations))
